# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev
variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dockerRegistryServiceConnection: '<SERVICE_CONNECTION_NAME>'
  imageRepository: '<IMAGE_NAME>'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  
pool:
 vmImage: 'windows-latest'
jobs:

# Build job and scan

- job: build
  displayName: Build

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk 8.0.x'
    inputs:
      version: 8.0.x

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

#  - task: DotNetCoreCLI@2
#    displayName: Test
#    inputs:
#      command: test
#      projects: '**/*.UnitTest.csproj'
#      arguments: '--configuration $(buildConfiguration)'
 
#- job: scan
#  displayName: Scan
#  dependsOn: build
#  pool:
#    vmImage: 'ubuntu-latest'
#  steps:
#  - task: QodanaScan@2024
#    env:
#      QODANA_TOKEN: $(QODANA_TOKEN)

- job: deploy
  displayName: Publish
  dependsOn: build
  pool:
    vmImage: 'windows-latest'
  steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Frontend_$(Build.BuildNumber)'
      publishLocation: 'Container'
    condition: succeededOrFailed()

  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'Dev/test 2 (2024.DI3.P3 G1.1)(5b7cf519-ec0c-474a-98f8-d77c061ef50f)'
      appName: 'frontdevvillajour'
      resourceGroupName: 'villajour'
      appSettings: |
        [
          {
          "name": "OpenIDConnectSettings__Authority",
          "value": "https://keycloak.villajour.fr:8443/realms/Villajour/",
          "slotSetting": false
          },
          {
          "name": "OpenIDConnectSettings__ClientId",
          "value": "dev-villajour-front-end",
          "slotSetting": false
          },
          {
          "name": "OpenIDConnectSettings__ClientSecret",
          "value": "$(OPENIDCONNECT:CLIENTSECRET)",
          "slotSetting": false
          }
        ]

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Dev/test 2 (2024.DI3.P3 G1.1)(5b7cf519-ec0c-474a-98f8-d77c061ef50f)'
      appType: 'webApp'
      WebAppName: 'frontdevvillajour'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      enableCustomDeployment: true
      DeploymentType: 'webDeploy'
      TakeAppOfflineFlag: false
